export interface StoreProduct {
  id: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  category: string;
  price: number;
  unit: string;
  stock: number;
  benefits: string[];
  ingredients: string[];
  usage: string;
  emoji: string;
  gradient: string;
  gradientCss: string;
  image?: string;
  badge?: string;
}

export const STORE_PRODUCTS: StoreProduct[] = [
  {
    id: "sp1",
    name: "Intandokazi Yothando",
    tagline: "Traditional love & wellness cream for skin & body",
    description: "A luxurious 250ml herbal cream handcrafted with traditional African botanicals to nourish, soften and restore your skin.",
    longDescription: "Intandokazi Yothando — meaning 'love' in Zulu — is a signature Nthandokazi Herbal cream blending time-honoured African plant extracts with rich moisturising agents. Applied daily, it deeply hydrates the skin, evens tone and leaves a soft, healthy glow. The traditional herbal formulation also supports circulation and skin renewal, making it a true all-in-one body treatment rooted in African healing wisdom.",
    category: "Skin & Body",
    price: 220,
    unit: "250ml tub",
    stock: 35,
    benefits: ["Deeply moisturises & softens skin", "Evens skin tone naturally", "Promotes healthy skin renewal", "Rich in traditional African botanicals", "Suitable for all skin types"],
    ingredients: ["Traditional African herbal extracts", "Shea butter", "Natural plant oils", "Vitamin E", "Aloe vera"],
    usage: "Apply generously to clean skin morning and evening. Massage in circular motions until absorbed. For best results use daily.",
    emoji: "💜",
    gradient: "from-purple-900 to-violet-800",
    gradientCss: "linear-gradient(135deg, #4a1d96, #5b21b6)",
    image: "/images/products/intandokazi-yothando.jpg",
    badge: "Best Seller",
  },
  {
    id: "sp2",
    name: "Mavula Kuvaliwe Scrub",
    tagline: "Exfoliating bath scrub for radiant, renewed skin",
    description: "A vibrant pink & blue 250ml exfoliating bath scrub infused with traditional herbs to deeply cleanse, exfoliate and revitalise your skin.",
    longDescription: "Mavula Kuvaliwe is a beautifully crafted two-tone exfoliating scrub that combines the cleansing power of traditional African herbs with gentle exfoliating particles. The pink layer softens and brightens while the blue layer detoxifies and refreshes. Together they remove dead skin cells, unclog pores and leave skin feeling silky smooth and deeply nourished. Perfect for a luxurious bath or shower ritual.",
    category: "Skin & Body",
    price: 195,
    unit: "250ml tub",
    stock: 42,
    benefits: ["Removes dead skin cells", "Unclogs pores & detoxifies", "Brightens & evens skin tone", "Deeply nourishes after exfoliation", "Leaves skin silky smooth"],
    ingredients: ["Exfoliating mineral particles", "Traditional herbal extracts", "Moisturising plant oils", "Glycerin", "Natural fragrance"],
    usage: "Apply to damp skin in the shower or bath. Massage gently in circular motions for 2–3 minutes. Rinse thoroughly. Use 2–3 times per week.",
    emoji: "🌸",
    gradient: "from-pink-800 to-sky-700",
    gradientCss: "linear-gradient(135deg, #9d174d, #0369a1)",
    image: "/images/products/mavula-kuvaliwe-scrub.jpg",
    badge: "New",
  },
  {
    id: "sp3",
    name: "Mavula Kuvaliwe Liquid",
    tagline: "Herbal liquid wash for a purifying bath experience",
    description: "A concentrated herbal liquid wash in convenient pouches, formulated with traditional African botanicals for deep cleansing and skin nourishment.",
    longDescription: "Mavula Kuvaliwe Liquid is a potent herbal bath and body wash that harnesses the cleansing and healing properties of traditional African plants. Available in easy-to-use pouches, this vibrant formula lathers richly to remove impurities while leaving skin feeling refreshed, soft and subtly scented. The traditional herbal blend supports skin health and provides a spa-like experience at home.",
    category: "Skin & Body",
    price: 175,
    unit: "per pouch",
    stock: 60,
    benefits: ["Deep cleansing & purifying", "Nourishes & softens skin", "Rich lather for full-body wash", "Traditional herbal healing properties", "Convenient pouch packaging"],
    ingredients: ["Traditional African herbal extracts", "Gentle surfactants", "Moisturising agents", "Glycerin", "Natural fragrance"],
    usage: "Squeeze a small amount onto a loofah or hands. Lather onto wet skin and massage gently. Rinse thoroughly with warm water.",
    emoji: "💧",
    gradient: "from-pink-700 to-rose-600",
    gradientCss: "linear-gradient(135deg, #be185d, #e11d48)",
    image: "/images/products/mavula-kuvaliwe-pouches.jpg",
  },
  {
    id: "sp4",
    name: "Mavula Kuvulle Liquid",
    tagline: "Purple herbal liquid for wellness & spiritual cleansing",
    description: "A distinctive purple herbal liquid combining traditional African botanicals for body cleansing, skin nourishment and spiritual wellness.",
    longDescription: "Mavula Kuvulle Liquid is a unique deep-purple herbal formulation that draws on centuries of African traditional healing. The rich purple colour comes from carefully selected botanical extracts known for their purifying and protective properties. Used as a bath additive or body wash, it cleanses the skin while promoting a sense of calm, protection and spiritual wellbeing — a truly holistic African wellness experience.",
    category: "Wellness & Spiritual",
    price: 210,
    unit: "500ml bottle",
    stock: 28,
    benefits: ["Deep body & spiritual cleansing", "Calming & protective properties", "Nourishes & conditions skin", "Traditional African botanical blend", "Promotes sense of wellbeing"],
    ingredients: ["Purple botanical extracts", "Traditional African herbs", "Cleansing agents", "Moisturising oils", "Natural fragrance"],
    usage: "Add a capful to bath water or apply directly to skin as a wash. For spiritual cleansing, use in a warm bath and allow to soak for 10–15 minutes.",
    emoji: "🔮",
    gradient: "from-violet-900 to-purple-800",
    gradientCss: "linear-gradient(135deg, #4c1d95, #6d28d9)",
    image: "/images/products/mavula-kuvulle-liquid.png",
    badge: "Traditional",
  },
  {
    id: "sp5",
    name: "Intandokazi Aakhanya Liquid",
    tagline: "Powerful 1-litre herbal tonic for strength & vitality",
    description: "A potent 1-litre Intandokazi Aakhanya herbal liquid tonic formulated to boost energy, strengthen the body and support overall health.",
    longDescription: "Intandokazi Aakhanya — meaning 'she who shines' — is a powerful concentrated herbal tonic in a generous 1-litre bottle. This deep amber liquid is crafted from a blend of traditional African medicinal plants selected for their ability to restore vitality, boost the immune system and support the body's natural healing processes. A staple in traditional African wellness, taken daily to maintain strength and radiant health.",
    category: "Internal Health",
    price: 320,
    unit: "1 litre bottle",
    stock: 20,
    benefits: ["Boosts energy & vitality", "Strengthens immune system", "Supports body's natural healing", "Rich in traditional medicinal plants", "Daily wellness tonic"],
    ingredients: ["Intandokazi herbal blend", "Traditional African plant extracts", "Purified water", "Natural preservatives"],
    usage: "Shake well before use. Take 20–30ml diluted in warm water twice daily, morning and evening. Refrigerate after opening.",
    emoji: "⚡",
    gradient: "from-blue-900 to-indigo-800",
    gradientCss: "linear-gradient(135deg, #1e3a8a, #3730a3)",
    image: "/images/products/intandokazi-aakhanya-liquid.jpg",
    badge: "Best Value",
  },
  {
    id: "sp6",
    name: "Inhlasohla Emplasmeni",
    tagline: "Traditional herbal emulsion powder for skin & healing",
    description: "A unique 200ml traditional herbal emulsion powder used for skin treatment, healing and traditional wellness rituals.",
    longDescription: "Inhlasohla Emplasmeni is a finely milled traditional herbal powder that has been used in Southern African healing for generations. When mixed with water or oil it forms a smooth emulsion that can be applied to the skin for healing, soothing and nourishing purposes. The sandy golden powder is rich in traditional plant compounds that support skin repair, reduce inflammation and promote healthy skin. Also used in traditional wellness and cleansing rituals.",
    category: "Traditional Healing",
    price: 185,
    unit: "200ml tub",
    stock: 30,
    benefits: ["Supports skin healing & repair", "Reduces skin inflammation", "Traditional cleansing properties", "Nourishes & conditions skin", "Used in traditional wellness rituals"],
    ingredients: ["Traditional African herbal powder blend", "Medicinal plant extracts", "Natural minerals", "No synthetic additives"],
    usage: "Mix a small amount with water or carrier oil to form a paste. Apply to affected area or use as a full-body treatment. Leave for 10–15 minutes then rinse.",
    emoji: "🌿",
    gradient: "from-amber-800 to-yellow-700",
    gradientCss: "linear-gradient(135deg, #92400e, #a16207)",
    image: "/images/products/inhlasohla-emplasmeni.jpg",
  },
  {
    id: "sp7",
    name: "Intanmorati Mandi & Voni",
    tagline: "Herbal shower & bath liquid for daily cleansing",
    description: "A premium 250ml purple herbal shower and bath liquid combining traditional botanicals for a luxurious daily cleansing experience.",
    longDescription: "Intanmorati Mandi & Voni — 'wash and bathe' — is a beautifully formulated herbal liquid designed for daily use in the shower or bath. The rich purple formula is packed with traditional African botanical extracts that cleanse deeply while conditioning and softening the skin. Its gentle yet effective formula is suitable for the whole family and leaves a subtle, pleasant herbal fragrance on the skin throughout the day.",
    category: "Skin & Body",
    price: 165,
    unit: "250ml bottle",
    stock: 48,
    benefits: ["Gentle daily cleansing", "Conditions & softens skin", "Traditional herbal fragrance", "Suitable for whole family", "Leaves skin feeling refreshed"],
    ingredients: ["Traditional African herbal extracts", "Gentle cleansing agents", "Conditioning agents", "Glycerin", "Natural fragrance"],
    usage: "Apply to wet skin or loofah. Lather and massage over body. Rinse thoroughly. Suitable for daily use.",
    emoji: "🛁",
    gradient: "from-purple-800 to-indigo-700",
    gradientCss: "linear-gradient(135deg, #6d28d9, #4338ca)",
    image: "/images/products/intanmorati-mandi-voni.jpg",
    badge: "Family Favourite",
  },
  {
    id: "sp8",
    name: "Intanmorati Body Butter",
    tagline: "Lavender & Vanilla body butter for silky smooth skin",
    description: "A rich whipped Intanmorati Body Butter in Lavender & Vanilla — a deeply moisturising treatment that melts into skin for lasting softness.",
    longDescription: "Intanmorati Body Butter in Lavender & Vanilla is a luxuriously rich whipped butter that delivers intense moisture to dry, thirsty skin. Formulated with a blend of nourishing butters and oils, it absorbs beautifully without leaving a greasy residue. The calming lavender and warm vanilla fragrance creates a spa-like experience while the formula works to restore the skin's natural moisture barrier, leaving it visibly softer, smoother and more radiant.",
    category: "Skin & Body",
    price: 240,
    unit: "250ml tub",
    stock: 25,
    benefits: ["Intense deep moisturisation", "Restores skin's moisture barrier", "Calming lavender & vanilla scent", "Non-greasy formula", "Visibly softer & smoother skin"],
    ingredients: ["Shea butter", "Cocoa butter", "Mango butter", "Lavender essential oil", "Vanilla extract", "Vitamin E oil"],
    usage: "Apply to clean skin after bathing while skin is still slightly damp. Massage in until fully absorbed. Use daily for best results, especially on dry areas.",
    emoji: "✨",
    gradient: "from-purple-200 to-violet-300",
    gradientCss: "linear-gradient(135deg, #7c3aed, #a78bfa)",
    image: "/images/products/intanmorati-body-butter.jpg",
    badge: "Premium",
  },
  {
    id: "sp9",
    name: "Nature's Essence Artisan Soaps",
    tagline: "100% natural handcrafted soaps with the Tree of Life",
    description: "Artisan handcrafted soaps made with 100% natural organic ingredients, featuring the signature Tree of Life design in a range of herbal varieties.",
    longDescription: "Nature's Essence Artisan Soaps are lovingly handcrafted using only the finest organic ingredients. Each bar features the beautiful Tree of Life design and is available in a range of varieties including deep cleansing charcoal, nourishing honey & oat, refreshing herbal green and moisturising clear glycerin. Free from synthetic chemicals, parabens and SLS, these soaps are gentle enough for sensitive skin while providing a truly luxurious lather.",
    category: "Skin & Body",
    price: 85,
    unit: "per bar",
    stock: 80,
    benefits: ["100% natural & organic ingredients", "Gentle on sensitive skin", "Rich luxurious lather", "No parabens or SLS", "Beautiful Tree of Life design"],
    ingredients: ["Organic plant oils", "Shea butter", "Natural botanical extracts", "Essential oils", "No synthetic chemicals"],
    usage: "Use as a regular hand or body soap. Lather with warm water and massage over skin. Rinse thoroughly. Store in a dry soap dish between uses.",
    emoji: "🌳",
    gradient: "from-stone-800 to-amber-700",
    gradientCss: "linear-gradient(135deg, #44403c, #b45309)",
    image: "/images/products/natures-essence-soaps.jpg",
    badge: "100% Natural",
  },
];

export const CATEGORIES = ["All", ...Array.from(new Set(STORE_PRODUCTS.map((p) => p.category)))];
