export interface StoreProduct {
  id: string;
  name: string;
  tagline: string;
  description: string;
  longDescription: string;
  category: string;
  price: number;
  unit: string;
  stock: number;
  benefits: string[];
  ingredients: string[];
  usage: string;
  emoji: string;
  gradient: string;
  gradientCss: string;
  image?: string;
  badge?: string;
}

export const STORE_PRODUCTS: StoreProduct[] = [
  {
    id: "sp1",
    name: "Imbiza Yamadoda",
    tagline: "Traditional herbal tonic for men's wellness",
    description: "A 500ml traditional herbal tonic blend with moringa, African potato, aloe ferox, and cancer bush for general wellness.",
    longDescription: "Imbiza Yamadoda is a traditional herbal tonic from Intandokazi Herbal, formulated with indigenous herbs including moringa, African potato (Hypoxis), aloe ferox, and cancer bush (Sutherlandia). This general wellness mixture supports vitality and overall health using time-honored African botanical wisdom.",
    category: "Internal Health",
    price: 280,
    unit: "500ml bottle",
    stock: 25,
    benefits: ["Supports general wellness", "Traditional African botanical blend", "Rich in indigenous herbs", "Promotes vitality", "Natural health support"],
    ingredients: ["Moringa", "African potato (Hypoxis)", "Aloe ferox", "Cancer bush (Sutherlandia)", "Traditional indigenous herbs"],
    usage: "Shake well. Take 2 tablespoons (30ml) twice daily after meals, or as directed by your health practitioner. Refrigerate after opening.",
    emoji: "💪",
    gradient: "from-amber-900 to-orange-800",
    gradientCss: "linear-gradient(135deg, #78350f, #9a3412)",
    image: "/images/products/imbiza-yamadoda.jpeg",
    badge: "Traditional",
  },
  {
    id: "sp2",
    name: "Imbiza yokuchatha",
    tagline: "Traditional cleansing mixture for lower-body wellness",
    description: "A 500ml traditional herbal cleansing mixture (ukuchatha) for isichitho sangaphansi - lower-body cleansing and wellness.",
    longDescription: "Imbiza yokuchatha is a traditional herbal cleansing mixture from Intandokazi Ukuphila Products, formulated for isichitho sangaphansi (lower-body cleansing). This herbal purgative/enema preparation follows traditional African wellness practices for internal cleansing and balance.",
    category: "Traditional Healing",
    price: 260,
    unit: "500ml bottle",
    stock: 20,
    benefits: ["Traditional cleansing support", "Lower-body wellness", "Herbal purgative preparation", "Follows traditional practices", "Internal balance support"],
    ingredients: ["Traditional African herbal blend", "Cleansing botanicals", "Natural plant extracts"],
    usage: "Mix half a glass of warm water with half a glass of umuthi. Use the mixture for ukuchatha (enema). Repeat twice a week, or as directed by your practitioner.",
    emoji: "🌿",
    gradient: "from-green-900 to-emerald-800",
    gradientCss: "linear-gradient(135deg, #14532d, #065f46)",
    image: "/images/products/imbiza-yokuchata.jpeg",
  },
  {
    id: "sp3",
    name: "Stop Nonsense! — Indlovu kayiphendulwa",
    tagline: "Traditional cleansing mixture for steam/sitz baths",
    description: "A 2-litre traditional herbal cleansing mixture for ukuchatha (steam/sitz cleansing) - powerful traditional wellness support.",
    longDescription: "Stop Nonsense! — Indlovu kayiphendulwa is a traditional herbal cleansing mixture from Intandokazi Ukuphila Products, formulated for ukuchatha (steam/sitz cleansing) use. This powerful 2-litre preparation supports traditional African cleansing rituals and wellness practices.",
    category: "Traditional Healing",
    price: 420,
    unit: "2 litre bottle",
    stock: 15,
    benefits: ["Powerful traditional cleansing", "Steam/sitz bath support", "Large 2-litre size", "Traditional wellness ritual", "Deep cleansing properties"],
    ingredients: ["Traditional African herbal blend", "Cleansing botanicals", "Natural plant extracts"],
    usage: "Pour 2 litres of umuthi into a bucket. Fill with warm water to make approximately 5 litres. Sit over the bucket and steam cleanse. Use 3-4 times a day, after every 2 days, or as directed.",
    emoji: "🔥",
    gradient: "from-red-900 to-orange-800",
    gradientCss: "linear-gradient(135deg, #7f1d1d, #9a3412)",
    image: "/images/products/stop-nonsence.jpeg",
    badge: "Powerful",
  },
  {
    id: "sp4",
    name: "Imbiza yoMhlume",
    tagline: "Traditional herbal tonic for internal cleansing",
    description: "A 1-litre traditional herbal tonic blend formulated for internal cleansing and strengthening.",
    longDescription: "Imbiza yoMhlume is a traditional herbal tonic from Intandokazi Ukuphila Products, formulated as an internal cleansing and strengthening mixture. This 1-litre preparation supports digestive wellness and overall vitality using traditional African botanical wisdom.",
    category: "Internal Health",
    price: 340,
    unit: "1 litre bottle",
    stock: 18,
    benefits: ["Internal cleansing support", "Strengthening properties", "Digestive wellness", "Traditional formulation", "Supports vitality"],
    ingredients: ["Traditional African herbal blend", "Cleansing botanicals", "Strengthening plant extracts"],
    usage: "Mix 2 tablespoons in a quarter cup of warm water. Drink three times a day, 30 minutes before meals, or as directed by your practitioner.",
    emoji: "⚡",
    gradient: "from-blue-900 to-cyan-800",
    gradientCss: "linear-gradient(135deg, #1e3a8a, #155e75)",
    image: "/images/products/imbiza-yomhlume.jpeg",
  },
  {
    id: "sp5",
    name: "Umabulala iDliso (Umlomo Omnandi)",
    tagline: "Traditional mixture for cleansing related to idliso",
    description: "A 1-litre traditional herbal mixture formulated for cleansing related to idliso (traditional concept of poison/bad luck).",
    longDescription: "Umabulala iDliso (Umlomo Omnandi) is a traditional herbal mixture from Intandokazi Ukuphila Products, formulated for cleansing related to idliso (traditional concept of poison/bad luck). This preparation follows traditional African wellness practices for spiritual and physical cleansing.",
    category: "Traditional Healing",
    price: 350,
    unit: "1 litre bottle",
    stock: 22,
    benefits: ["Traditional cleansing support", "Spiritual wellness", "Physical cleansing", "Follows traditional practices", "Protective properties"],
    ingredients: ["Traditional African herbal blend", "Cleansing botanicals", "Protective plant extracts"],
    usage: "Take 2 tablespoons 3 times a day after meals, or as directed by your practitioner. Not for use during pregnancy.",
    emoji: "🛡️",
    gradient: "from-purple-900 to-violet-800",
    gradientCss: "linear-gradient(135deg, #4c1d95, #5b21b6)",
    image: "/images/products/umabulala-idliso.jpeg",
  },
  {
    id: "sp6",
    name: "Umhlabelo",
    tagline: "Traditional herbal wash for home and body cleansing",
    description: "A 1-litre traditional herbal wash for ukuhlabela (ritual cleansing/washing) of the home and body.",
    longDescription: "Umhlabelo is a traditional herbal wash from Intandokazi Ukuphila Products, formulated for ukuhlabela (ritual cleansing/washing) of the home and body. This preparation supports traditional African cleansing rituals for spiritual protection and wellness.",
    category: "Wellness & Spiritual",
    price: 330,
    unit: "1 litre bottle",
    stock: 28,
    benefits: ["Home and body cleansing", "Ritual washing support", "Spiritual protection", "Traditional formulation", "Day and night use"],
    ingredients: ["Traditional African herbal blend", "Cleansing botanicals", "Protective plant extracts"],
    usage: "Wash/cleanse home and body with warm water, night and day for 7 days, or as directed by your practitioner.",
    emoji: "🏠",
    gradient: "from-teal-900 to-cyan-800",
    gradientCss: "linear-gradient(135deg, #134e4a, #155e75)",
    image: "/images/products/umhlabelo.jpeg",
  },
  {
    id: "sp7",
    name: "Imbiza Yama-Ulcer",
    tagline: "Traditional mixture for digestive comfort",
    description: "A 1-litre traditional herbal mixture formulated to support digestive comfort and general wellness.",
    longDescription: "Imbiza Yama-Ulcer is a traditional herbal mixture from Intandokazi Ukuphila Products, formulated to support digestive comfort and general wellness. This preparation uses traditional African botanicals known for their soothing and healing properties.",
    category: "Internal Health",
    price: 360,
    unit: "1 litre bottle",
    stock: 16,
    benefits: ["Digestive comfort support", "Soothing properties", "General wellness", "Traditional formulation", "Natural healing support"],
    ingredients: ["Traditional African herbal blend", "Soothing botanicals", "Digestive support plant extracts"],
    usage: "Take 2 tablespoons 3 times a day after meals, or as directed by your practitioner. Consult healthcare provider if you have ulcer diagnosis.",
    emoji: "💚",
    gradient: "from-lime-900 to-green-800",
    gradientCss: "linear-gradient(135deg, #365314, #166534)",
    image: "/images/products/imbiza-yama-ulcer-.jpeg",
  },
  {
    id: "sp8",
    name: "Umvusa Nkunzi",
    tagline: "Traditional men's vitality and strength tonic",
    description: "A 1-litre traditional herbal tonic formulated as a men's vitality and strength mixture.",
    longDescription: "Umvusa Nkunzi is a traditional herbal tonic from Intandokazi Ukuphila Products, formulated as a men's vitality and strength mixture. This powerful preparation supports male wellness, energy, and vitality using traditional African botanical wisdom.",
    category: "Internal Health",
    price: 380,
    unit: "1 litre bottle",
    stock: 20,
    benefits: ["Men's vitality support", "Strength and energy", "Traditional formulation", "Male wellness", "Natural vitality boost"],
    ingredients: ["Traditional African herbal blend", "Vitality-supporting botanicals", "Strengthening plant extracts"],
    usage: "Take 2 tablespoons 3 times a day after meals, or as directed by your practitioner.",
    emoji: "🦁",
    gradient: "from-orange-900 to-amber-800",
    gradientCss: "linear-gradient(135deg, #7c2d12, #92400e)",
    image: "/images/products/umvusa-nkunizi.jpeg",
    badge: "Men's Health",
  },
  {
    id: "sp9",
    name: "Zakhanya Liquid",
    tagline: "Traditional mixture for wellbeing and vitality",
    description: "A 1-litre traditional herbal mixture formulated to support general wellbeing and vitality.",
    longDescription: "Zakhanya Liquid is a traditional herbal mixture from Intandokazi Ukuphila Products, formulated to support general wellbeing and vitality. This preparation uses traditional African botanicals to promote health, energy, and overall wellness.",
    category: "Internal Health",
    price: 340,
    unit: "1 litre bottle",
    stock: 24,
    benefits: ["General wellbeing support", "Vitality boost", "Energy support", "Traditional formulation", "Overall wellness"],
    ingredients: ["Traditional African herbal blend", "Vitality-supporting botanicals", "Wellness plant extracts"],
    usage: "Take 2 tablespoons 3 times a day after meals, or as directed by your practitioner.",
    emoji: "✨",
    gradient: "from-yellow-900 to-amber-800",
    gradientCss: "linear-gradient(135deg, #713f12, #92400e)",
    image: "/images/products/zakhanyisa-liquid.jpeg",
  },
  {
    id: "sp10",
    name: "Bath Salt (Yokuthandeka)",
    tagline: "Herbal bath salt for attractiveness and likability",
    description: "A 500ml herbal bath salt formulated for cleansing baths and skin care to support ukuthandeka (attractiveness/likability).",
    longDescription: "Bath Salt (Yokuthandeka) is a herbal bath salt from Intandokazi Ukuphila Products, formulated for cleansing baths and skin care to support ukuthandeka (attractiveness/likability). This traditional preparation combines cleansing and beautifying properties for a complete wellness experience.",
    category: "Skin & Body",
    price: 220,
    unit: "500ml container",
    stock: 35,
    benefits: ["Cleansing bath support", "Skin care properties", "Attractiveness support", "Traditional formulation", "Beautifying properties"],
    ingredients: ["Herbal bath salts", "Traditional botanicals", "Skin-nourishing minerals"],
    usage: "Apply/rub on the body while bathing, or dissolve desired amount in warm bath water and soak as needed.",
    emoji: "💖",
    gradient: "from-pink-900 to-rose-800",
    gradientCss: "linear-gradient(135deg, #831843, #9f1239)",
    image: "/images/products/yokuthandeka.jpeg",
    badge: "Beauty",
  },
  {
    id: "sp11",
    name: "Inhlanhla Emhlophe",
    tagline: "Herbal bath salt for luck and fortune",
    description: "A 500ml herbal bath salt formulated for cleansing baths associated with inhlanhla (luck/fortune).",
    longDescription: "Inhlanhla Emhlophe is a herbal bath salt from Intandokazi Ukuphila Products, formulated for cleansing baths associated with inhlanhla (luck/fortune). This traditional preparation supports spiritual wellness and attracts positive energy.",
    category: "Wellness & Spiritual",
    price: 240,
    unit: "500ml container",
    stock: 30,
    benefits: ["Luck and fortune support", "Spiritual cleansing", "Positive energy attraction", "Traditional formulation", "Wellness bath"],
    ingredients: ["Herbal bath salts", "Traditional botanicals", "Fortune-attracting minerals"],
    usage: "Apply/rub on the body while bathing, or dissolve desired amount in warm bath water and soak as needed.",
    emoji: "🍀",
    gradient: "from-slate-200 to-gray-300",
    gradientCss: "linear-gradient(135deg, #e2e8f0, #d1d5db)",
    image: "/images/products/inhlanhla-emhlophe.jpeg",
  },
  {
    id: "sp12",
    name: "Umakhiphi Isichitho",
    tagline: "Herbal bath salt for removing misfortune",
    description: "A 500ml herbal bath salt formulated for cleansing baths associated with removing isichitho (misfortune/negative energy).",
    longDescription: "Umakhiphi Isichitho is a herbal bath salt from Intandokazi Ukuphila Products, formulated for cleansing baths associated with removing isichitho (misfortune/negative energy). This powerful traditional preparation supports spiritual cleansing and protection.",
    category: "Wellness & Spiritual",
    price: 250,
    unit: "500ml container",
    stock: 28,
    benefits: ["Removes misfortune", "Spiritual cleansing", "Negative energy removal", "Traditional formulation", "Protection support"],
    ingredients: ["Herbal bath salts", "Traditional cleansing botanicals", "Protective minerals"],
    usage: "Apply/rub on the body while bathing, or dissolve desired amount in warm bath water and soak as needed.",
    emoji: "🛡️",
    gradient: "from-indigo-900 to-purple-800",
    gradientCss: "linear-gradient(135deg, #312e81, #6d28d9)",
    image: "/images/products/umakhiphi-isichitho.jpeg",
    badge: "Protection",
  },
  {
    id: "sp13",
    name: "Tissue Oil (Eyenenhlannhla)",
    tagline: "Herbal tissue oil for luck and skin nourishment",
    description: "A 100ml herbal tissue oil formulated for skin nourishment and associated with inhlanhla (luck/fortune).",
    longDescription: "Tissue Oil (Eyenenhlannhla) is a herbal tissue oil from Intandokazi Ukuphila Products, formulated for skin nourishment and associated with inhlanhla (luck/fortune). This traditional preparation combines skincare benefits with spiritual wellness support.",
    category: "Skin & Body",
    price: 180,
    unit: "100ml bottle",
    stock: 40,
    benefits: ["Skin nourishment", "Luck and fortune support", "Moisturizing properties", "Traditional formulation", "Spiritual wellness"],
    ingredients: ["Herbal tissue oil blend", "Traditional botanicals", "Skin-nourishing oils"],
    usage: "Apply when you anoint/rub the whole body. Massage a small amount into clean, dry skin as needed.",
    emoji: "🌟",
    gradient: "from-amber-600 to-yellow-500",
    gradientCss: "linear-gradient(135deg, #d97706, #eab308)",
    image: "/images/products/tissue-oil-eyenenhlannhla.jpeg",
  },
  {
    id: "sp14",
    name: "Tissue Oil (Yesichitho)",
    tagline: "Herbal tissue oil for removing misfortune",
    description: "A 100ml herbal tissue oil formulated for skin nourishment and associated with removing isichitho (misfortune/negative energy).",
    longDescription: "Tissue Oil (Yesichitho) is a herbal tissue oil from Intandokazi Ukuphila Products, formulated for skin nourishment and associated with removing isichitho (misfortune/negative energy). This traditional preparation combines skincare benefits with spiritual cleansing support.",
    category: "Skin & Body",
    price: 180,
    unit: "100ml bottle",
    stock: 38,
    benefits: ["Skin nourishment", "Removes misfortune", "Moisturizing properties", "Traditional formulation", "Spiritual cleansing"],
    ingredients: ["Herbal tissue oil blend", "Traditional cleansing botanicals", "Skin-nourishing oils"],
    usage: "Apply when you anoint/rub the whole body. Massage a small amount into clean, dry skin as needed.",
    emoji: "🔮",
    gradient: "from-violet-900 to-purple-800",
    gradientCss: "linear-gradient(135deg, #4c1d95, #6d28d9)",
    image: "/images/products/tissue-oil-yesichitho.jpeg",
  },
  {
    id: "sp15",
    name: "Shower Gel (Ikhipha Isichitho)",
    tagline: "Herbal shower gel for removing misfortune",
    description: "A 500ml herbal shower gel formulated for daily cleansing and associated with removing isichitho (misfortune/negative energy).",
    longDescription: "Shower Gel (Ikhipha Isichitho) is a herbal shower gel from Intandokazi Ukuphila Products, formulated for daily cleansing and associated with removing isichitho (misfortune/negative energy). This traditional preparation combines daily hygiene with spiritual cleansing support.",
    category: "Skin & Body",
    price: 200,
    unit: "500ml bottle",
    stock: 32,
    benefits: ["Daily cleansing", "Removes misfortune", "Gentle on skin", "Traditional formulation", "Spiritual cleansing"],
    ingredients: ["Herbal shower gel base", "Traditional cleansing botanicals", "Gentle cleansing agents"],
    usage: "Wash the whole body. Apply a small amount to wet skin or sponge, lather, then rinse thoroughly.",
    emoji: "🚿",
    gradient: "from-blue-900 to-indigo-800",
    gradientCss: "linear-gradient(135deg, #1e3a8a, #3730a3)",
    image: "/images/products/shower-gel-ikhipha-isichitho.jpeg",
  },
  {
    id: "sp16",
    name: "Shower Gel (Yokuthandeka)",
    tagline: "Herbal shower gel for love and attraction",
    description: "A 500ml herbal shower gel formulated for daily cleansing and associated with uthando (love/attraction).",
    longDescription: "Shower Gel (Yokuthandeka) is a herbal shower gel from Intandokazi Ukuphila Products, formulated for daily cleansing and associated with uthando (love/attraction). This traditional preparation combines daily hygiene with attractiveness and likability support.",
    category: "Skin & Body",
    price: 200,
    unit: "500ml bottle",
    stock: 34,
    benefits: ["Daily cleansing", "Love and attraction support", "Gentle on skin", "Traditional formulation", "Beautifying properties"],
    ingredients: ["Herbal shower gel base", "Traditional botanicals", "Gentle cleansing agents"],
    usage: "Wash the whole body. Apply a small amount to wet skin or sponge, lather, then rinse thoroughly.",
    emoji: "💕",
    gradient: "from-pink-800 to-rose-700",
    gradientCss: "linear-gradient(135deg, #9f1239, #be123c)",
    image: "/images/products/shower-gel-yokuthandeka.jpeg",
  },
  {
    id: "sp17",
    name: "Umkhanyakude Jelly (Vaseline)",
    tagline: "Herbal petroleum jelly for skin protection",
    description: "A 250ml herbal petroleum jelly used for skin protection, moisturising and traditional applications.",
    longDescription: "Umkhanyakude Jelly (Vaseline) is a herbal petroleum jelly from Intandokazi Ukuphila Products, used for skin protection, moisturising and traditional applications. This versatile preparation provides deep moisturization and skin barrier protection.",
    category: "Skin & Body",
    price: 160,
    unit: "250ml container",
    stock: 45,
    benefits: ["Skin protection", "Deep moisturization", "Barrier protection", "Traditional formulation", "Versatile use"],
    ingredients: ["Herbal petroleum jelly base", "Traditional botanicals", "Moisturizing agents"],
    usage: "Apply a small amount to clean, dry skin and massage gently. Use as needed on hands, feet, elbows, lips or any dry areas.",
    emoji: "🧴",
    gradient: "from-cyan-900 to-blue-800",
    gradientCss: "linear-gradient(135deg, #164e63, #1e40af)",
    image: "/images/products/umkhanyakude-jelly-vaseline.jpeg",
  },
  {
    id: "sp18",
    name: "Umakhiphi Isichitho Vaseline",
    tagline: "Herbal petroleum jelly for removing misfortune",
    description: "A 250ml herbal petroleum jelly used for skin protection, moisturising and traditional applications associated with removing isichitho.",
    longDescription: "Umakhiphi Isichitho Vaseline is a herbal petroleum jelly from Intandokazi Ukuphila Products, used for skin protection, moisturising and traditional applications associated with removing isichitho (misfortune/negative energy). This preparation combines skincare benefits with spiritual cleansing support.",
    category: "Wellness & Spiritual",
    price: 170,
    unit: "250ml container",
    stock: 42,
    benefits: ["Skin protection", "Removes misfortune", "Deep moisturization", "Traditional formulation", "Spiritual cleansing"],
    ingredients: ["Herbal petroleum jelly base", "Traditional cleansing botanicals", "Moisturizing agents"],
    usage: "Apply a small amount to clean, dry skin and massage gently. Use as needed on hands, feet, elbows, lips or any dry areas.",
    emoji: "✨",
    gradient: "from-purple-900 to-indigo-800",
    gradientCss: "linear-gradient(135deg, #581c87, #3730a3)",
    image: "/images/products/umakhiphi-isichitho-vaseline.jpeg",
  },
];

export const CATEGORIES = ["All", ...Array.from(new Set(STORE_PRODUCTS.map((p) => p.category)))];
